version: '3.8'
services:
  materialjs:
    image: materialjs:latest
    container_name: materialjs
    build:
      context: .
      target: ${build_target:-dev}
    ports:
      - 80:8080
    volumes:
      - .:/node/service:delegated
      - ./.docker/nginx/logs:/node/logs:delegated
    environment:
      DEBUG: materialjs:*
      NODE_ENV: ${node_env:-development}
      VITE_MODE: ${vite_mode:-development}
      SERVER_PORT: 3000