name: Dev Push

on:
  push:
    branches:
      - dev

jobs:
  test:
    uses: cosmicmind/github-actions/.github/workflows/docker-test.yml@release
    secrets:
      npm_token: ${{ secrets.npm_token }}