name: Dev Push

on:
  push:
    branches:
      - dev

jobs:
  dev-build:
    uses: cosmicmind/actions/.github/workflows/docker-dev.yml@release
  test:
    needs: dev-build
    uses: cosmicmind/actions/.github/workflows/test.yml@release