name: Dev Push

on:
  push:
    branches:
      - dev

jobs:
  build:
    uses: cosmicmind/github-actions/.github/workflows/docker-dev.yml@release
    secrets:
      npm_token: ${{ secrets.npm_token }}
  test:
    needs: build
    uses: cosmicmind/github-actions/.github/workflows/test.yml@release