name: Dev Push

on:
  push:
    branches:
      - dev

jobs:
  dev-build:
    uses: cosmicmind/actions/.github/workflows/dev-build.yml@release
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  test:
    needs: dev-build
    uses: cosmicmind/actions/.github/workflows/test.yml@release
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}