name: Feature Push

on:
  push:
    branches-ignore:
      - dev
      - release

jobs:
  lint:
    uses: cosmicmind/github-actions/.github/workflows/lint.yml@release
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  codeql:
    uses: cosmicmind/github-actions/.github/workflows/codeql.yml@release