name: Release Push

on:
  push:
    branches:
      - release

jobs:
  package-publish:
    uses: cosmicmind/github-actions/.github/workflows/package-publish.yml@release
    secrets:
      npm_token: ${{ secrets.npm_token }}