name: Release Pull Request

on:
  pull_request:
    branches:
      - release

jobs:
  lint:
    uses: cosmicmind/actions/.github/workflows/lint.yml@release
  codeql:
    needs: lint
    uses: cosmicmind/actions/.github/workflows/codeql.yml@release
  release-build:
    needs: codeql
    uses: cosmicmind/actions/.github/workflows/release-build.yml@release
  test:
    needs: release-build
    uses: cosmicmind/actions/.github/workflows/test.yml@release