name: Release Pull Request

on:
  pull_request:
    branches:
      - release

jobs:
  release:
    uses: cosmicmind/github-actions/.github/workflows/docker-release.yml@release
    secrets:
      npm_token: ${{ secrets.npm_token }}