name: Release Push

on:
  push:
    branches:
      - release

jobs:
  package-publish:
    uses: cosmicmind/actions/.github/workflows/package-publish.yml@release
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}